import React from 'react';
import {
  IconDrop,
  IconBolt,
  IconTools,
  IconHome,
  IconBuilding,
  IconGear,
  IconCctv,
  IconClock,
  IconSofa,
  IconWindow,
  IconPaintRoller,
  IconTexture,
  IconPolish,
  IconTiles,
  IconKitchen,
  IconBath,
  IconCeiling,
  IconWallPanel,
  IconGrcPanel,
  IconCarton,
  IconGlass,
  IconDecor,
  IconFloorPolish,
  IconCleaning,
} from './Icons';

export const servicesList = [
  {
    id: '01',
    slug: 'full-home-renovation',
    category: 'renovation',
    badge: 'Turnkey Makeover',
    tagline: 'Complete Villa & Flat Renovation',
    title: 'Full Home Renovation',
    timeline: '2–4 Weeks Turnaround',
    image: '/Services/Home Renovation.png',
    icon: <IconHome className="w-5 h-5" />,
    desc: 'Complete home upgrades managed end-to-end. We take care of demolition, porcelain tiling, false ceilings, lighting, and custom joinery with zero headache.',
    features: [
      'Complete apartment and villa makeovers',
      'Open-concept kitchen and living layouts',
      'Italian & Spanish porcelain floor tiling',
      'Gypsum false ceilings with indirect warm LED lights',
    ],
    highlights: ['Turnkey Scope', 'Free 3D Layout', '1-Yr Warranty'],
  },
  {
    id: '02',
    slug: 'plumbing-bathroom-remodel',
    category: 'mep',
    badge: 'Fast 5–7 Days',
    tagline: 'Modern Bathrooms & Pipe Repairs',
    title: 'Plumbing & Bathroom Remodel',
    timeline: 'Prompt Same-Day Response',
    image: '/Services/Plumbing.webp',
    icon: <IconDrop className="w-5 h-5" />,
    desc: 'From fixing stubborn concealed leaks to building modern walk-in rain showers. Our licensed plumbers install fixtures that look stunning and never leak.',
    features: [
      'Concealed pipe leak detection and re-piping',
      'Walk-in glass shower enclosures and rain showers',
      'Modern floating vanity units and toilets',
      'Central water heater replacement and booster pumps',
    ],
    highlights: ['Leak Free Guarantee', 'Grohe / Kohler', 'Clean Finish'],
  },
  {
    id: '03',
    slug: 'electrical-lighting',
    category: 'mep',
    badge: 'Certified Safe',
    tagline: 'Rewiring, DB Boxes & Chandeliers',
    title: 'Electrical & Modern Lighting',
    timeline: 'Safe & Certified Work',
    image: '/Services/Electrical.png',
    icon: <IconBolt className="w-5 h-5" />,
    desc: 'Keep your property safe with clean electrical work. We handle distribution board (DB) upgrades, complete rewiring, architectural LED strips, and chandeliers.',
    features: [
      'Distribution board (DB) circuit breaker upgrades',
      'Safe whole-home rewiring and extra wall sockets',
      'Heavy chandelier installation and magnetic track lights',
      'Smart switches, dimmers, and ambient mood lighting',
    ],
    highlights: ['Certified Electricians', 'Fire Safe Cable', 'Load Tested'],
  },
  {
    id: '04',
    slug: 'custom-carpentry-joinery',
    category: 'woodwork',
    badge: 'In-House Workshop',
    tagline: 'Made-To-Measure Cabinets & Wardrobes',
    title: 'Custom Carpentry & Joinery',
    timeline: 'Factory Direct Quality',
    image: '/Services/Carpenter.webp',
    icon: <IconTools className="w-5 h-5" />,
    desc: 'Custom furniture manufactured in our local workshop to fit your exact room measurements. Soft-close hinges, premium veneers, and durable moisture-resistant wood.',
    features: [
      'Modular kitchen cabinets with quartz countertops',
      'Floor-to-ceiling built-in wardrobes and walk-ins',
      'Solid wood interior doors with magnetic latches',
      'Fluted acoustic wood paneling and media feature walls',
    ],
    highlights: ['German Soft-Close', 'Custom Sizing', 'Durable Wood'],
  },
  {
    id: '05',
    slug: 'civil-construction-works',
    category: 'civil',
    badge: 'Solid Structural Quality',
    tagline: 'Acoustic Walls, Extensions & Screeding',
    title: 'Civil & Construction Works',
    timeline: 'Precise Clean Work',
    image: '/Services/Construction.png',
    icon: <IconBuilding className="w-5 h-5" />,
    desc: 'Need an extra bedroom, home office, or room extension? We build sound-insulated gypsum partitions, blockwork walls, floor screeding, and outdoor tiling.',
    features: [
      'Soundproof gypsum wall partitions with glass wool',
      'Room extensions and internal wall removals',
      'Precision laser floor screeding and leveling',
      'Balcony expansion, waterproofing, and patio tiling',
    ],
    highlights: ['Acoustic Rated', 'Smooth Finish', 'Structural Care'],
  },
  {
    id: '06',
    slug: 'metal-fabrication-gates',
    category: 'fabrication',
    badge: 'Custom Fabricated',
    tagline: 'Villa Driveway Gates, Railings & Stairs',
    title: 'Metal Fabrication & Gates',
    timeline: 'Rust-Proof Powder Coating',
    image: '/Services/Fabrication.png',
    icon: <IconGear className="w-5 h-5" />,
    desc: 'Strong, stylish metalwork custom-welded to your specifications. Automatic motorized driveway gates, stainless steel stair railings, and modern pergolas.',
    features: [
      'Custom motorized sliding & swinging villa driveway gates',
      'Stainless steel 316 and tempered glass balcony railings',
      'Custom metal staircases and outdoor patio pergolas',
      'Window security grills and aluminum shade structures',
    ],
    highlights: ['Rust Protected', 'Italian Motors', 'Heavy Duty Steel'],
  },
  {
    id: '07',
    slug: 'cctv-camera-installation',
    category: 'mep',
    badge: 'Live Mobile Access',
    tagline: 'HD Cameras, Video Doorbells & Access',
    title: 'CCTV & Camera Installation',
    timeline: 'Clean Concealed Wiring',
    image: '/Services/Camera Installation.png',
    icon: <IconCctv className="w-5 h-5" />,
    desc: 'Monitor your villa or apartment 24/7 from your smartphone. We install high-resolution 4K night-vision cameras, smart video doorbells, and digital biometric locks.',
    features: [
      '4K ultra HD cameras with color night vision',
      'Instant mobile phone alerts on iOS & Android',
      'Smart video doorbells and biometric fingerprint locks',
      'Villa perimeter coverage with hidden cabling',
    ],
    highlights: ['Hikvision / Dahua', 'Mobile App Setup', 'Concealed Cables'],
  },
  {
    id: '08',
    slug: 'interior-design',
    category: 'interior',
    badge: 'Concept To Reality',
    tagline: 'Custom Interior Styling & Space Planning',
    title: 'Interior Design',
    timeline: 'Design in 1–2 Weeks',
    image: '/Services/Interior Design.svg',
    icon: <IconSofa className="w-5 h-5" />,
    desc: 'Full interior design service covering space planning, material selection, and styling for homes and offices. Our designers create a look that matches your lifestyle and budget before any work begins on site.',
    features: [
      'Personalized 2D layout and 3D visualization',
      'Color palette, furniture and lighting selection',
      'Material and finish moodboards before purchase',
      'Design supervision during execution',
    ],
    highlights: ['Free Concept', '3D Visuals', 'Budget Friendly'],
  },
  {
    id: '09',
    slug: 'upvc-window-installation',
    category: 'windows',
    badge: 'Energy Efficient',
    tagline: 'UPVC & Aluminum Window Systems',
    title: 'UPVC Window Installation',
    timeline: 'Fitted in 1–3 Days',
    image: '/Services/UPVC Window Installation.svg',
    icon: <IconWindow className="w-5 h-5" />,
    desc: 'Supply and installation of UPVC and aluminum windows that seal out heat, dust and noise. Built with reinforced multi-chamber profiles and double-glazed glass for lasting performance.',
    features: [
      'Double-glazed, sound and heat insulated glass',
      'Sliding, casement and fixed window systems',
      'Weatherproof rubber sealing and reinforced frames',
      'Mosquito mesh and safety lock fittings',
    ],
    highlights: ['Heat & Noise Insulated', 'Custom Sizes', 'Leak Free Seal'],
  },
  {
    id: '10',
    slug: 'interior-exterior-painting',
    category: 'painting',
    badge: 'Fresh Finish',
    tagline: 'Interior Walls & Exterior Facades',
    title: 'Painting – Interior & Exterior',
    timeline: '2–5 Days Turnaround',
    image: '/Services/Interior and Exterior Painting.svg',
    icon: <IconPaintRoller className="w-5 h-5" />,
    desc: 'Professional painting for interior walls, ceilings and exterior facades using weather-resistant, low-VOC paints. We prep surfaces properly so the finish stays smooth and long-lasting.',
    features: [
      'Crack filling, sanding and primer preparation',
      'Weatherproof exterior emulsion for facades',
      'Low-VOC interior paints safe for families',
      'Neat masking and dust-protected work areas',
    ],
    highlights: ['Low VOC Paint', 'Weatherproof', 'Clean Masking'],
  },
  {
    id: '11',
    slug: 'texture-and-dco-paint',
    category: 'painting',
    badge: 'Designer Walls',
    tagline: 'Decorative Textures & Dco Finishes',
    title: 'Texture Paint & Dco Paint',
    timeline: '3–6 Days Turnaround',
    image: '/Services/Texture and Dco Paint.svg',
    icon: <IconTexture className="w-5 h-5" />,
    desc: 'Decorative texture and Dco paint finishes that turn a plain wall into a feature wall. From stone-effect textures to smooth metallic Dco coats, applied by experienced finishers.',
    features: [
      'Stone, sand and stucco texture effects',
      'Metallic and pearl Dco paint finishes',
      'Custom feature wall patterns and stencils',
      'Sealed, scrub-resistant topcoat',
    ],
    highlights: ['Feature Walls', 'Scrub Resistant', 'Custom Patterns'],
  },
  {
    id: '12',
    slug: 'wood-polishing',
    category: 'woodwork',
    badge: 'Restored Shine',
    tagline: 'Furniture, Doors & Wood Flooring Polish',
    title: 'Wood Polish',
    timeline: '1–3 Days Turnaround',
    image: '/Services/Wood Polish.svg',
    icon: <IconPolish className="w-5 h-5" />,
    desc: 'Restore the natural shine of doors, furniture and wooden flooring with professional sanding, staining and polishing. We revive old wood or protect new woodwork against daily wear.',
    features: [
      'Sanding and scratch/dent repair',
      'PU, melamine and matte polish options',
      'Color staining to match existing wood tone',
      'Protective sealant against moisture and termites',
    ],
    highlights: ['PU & Melamine', 'Termite Protection', 'Color Matching'],
  },
  {
    id: '13',
    slug: 'tiles-work',
    category: 'civil',
    badge: 'Precision Laid',
    tagline: 'Floor, Wall & Outdoor Tiling',
    title: 'Tiles Work',
    timeline: '3–7 Days Turnaround',
    image: '/Services/Tiles Work.svg',
    icon: <IconTiles className="w-5 h-5" />,
    desc: 'Floor, wall and outdoor tiling with porcelain, ceramic, marble and mosaic tiles, laid with precise leveling and grouting. Includes old tile removal and surface preparation.',
    features: [
      'Porcelain, ceramic, marble and mosaic laying',
      'Old tile removal and floor leveling',
      'Waterproofing before bathroom and balcony tiling',
      'Clean, uniform grout lines and edge finishing',
    ],
    highlights: ['Laser Leveled', 'Waterproofed', 'Uniform Grouting'],
  },
  {
    id: '14',
    slug: 'kitchen-renovation',
    category: 'renovation',
    badge: 'Complete Makeover',
    tagline: 'Modular Kitchens & Countertop Upgrades',
    title: 'Kitchen Renovation',
    timeline: '1–3 Weeks Turnaround',
    image: '/Services/Kitchen Renovation.svg',
    icon: <IconKitchen className="w-5 h-5" />,
    desc: 'Complete kitchen makeovers from modular cabinets to quartz countertops and new plumbing/electrical points. We manage the full renovation so your kitchen is upgraded with zero hassle.',
    features: [
      'Modular cabinets with soft-close hardware',
      'Quartz and granite countertop installation',
      'Sink, hob and chimney plumbing/electrical points',
      'Backsplash tiling and under-cabinet lighting',
    ],
    highlights: ['Modular Design', 'Quartz Tops', '1-Yr Warranty'],
  },
  {
    id: '15',
    slug: 'bathroom-renovation',
    category: 'renovation',
    badge: 'Fast 5–7 Days',
    tagline: 'Full Washroom Makeovers',
    title: 'Bathroom Renovation',
    timeline: '5–7 Days Turnaround',
    image: '/Services/Bathroom Renovation.svg',
    icon: <IconBath className="w-5 h-5" />,
    desc: 'Full bathroom makeovers covering tiling, waterproofing, vanities and modern fittings. We handle demolition to final handover so your new washroom is ready to use fast.',
    features: [
      'Waterproofing and re-piping before tiling',
      'Modern vanities, mirrors and rain showers',
      'Anti-skid floor tiles and wall tiling',
      'New sanitaryware and concealed flush fittings',
    ],
    highlights: ['Waterproof Guarantee', 'Anti-Skid Tiles', 'Modern Fittings'],
  },
  {
    id: '16',
    slug: 'false-ceiling',
    category: 'civil',
    badge: 'Clean Modern Look',
    tagline: 'Gypsum False Ceilings & Cove Lighting',
    title: 'False Ceiling',
    timeline: '2–4 Days Turnaround',
    image: '/Services/False Ceiling.svg',
    icon: <IconCeiling className="w-5 h-5" />,
    desc: 'Gypsum false ceilings with cove and indirect LED lighting that hide wiring and give rooms a clean, modern finish. Designed for living rooms, bedrooms, offices and ceiling repairs.',
    features: [
      'Flat, tray and curved gypsum ceiling designs',
      'Indirect cove LED lighting channels',
      'Moisture-resistant boards for kitchens and bathrooms',
      'Smooth putty finish ready for paint',
    ],
    highlights: ['LED Cove Lighting', 'Moisture Resistant', 'Smooth Finish'],
  },
  {
    id: '17',
    slug: 'wall-paneling-and-cladding',
    category: 'interior',
    badge: 'Textured Feature Walls',
    tagline: 'Interior & Exterior Cladding Panels',
    title: 'Wall Paneling & Cladding',
    timeline: '3–6 Days Turnaround',
    image: '/Services/Wall Paneling and Cladding.svg',
    icon: <IconWallPanel className="w-5 h-5" />,
    desc: "Wood, PVC, WPC and stone-effect wall paneling and cladding for interior feature walls and exterior facades. Adds texture, insulation and a premium finish to any wall.",
    features: [
      'WPC, PVC and veneer wall panel installation',
      'Exterior weatherproof cladding facades',
      'Acoustic and fluted panel feature walls',
      'Hidden fixing for a seamless joint-free look',
    ],
    highlights: ['Weatherproof', 'Acoustic Rated', 'Seamless Fixing'],
  },
  {
    id: '18',
    slug: 'grc-panel-work',
    category: 'civil',
    badge: 'Architectural Facades',
    tagline: 'Glass Reinforced Concrete Panels',
    title: 'GRC Panel Work',
    timeline: 'Project-Based Timeline',
    image: '/Services/GRC Panel Work.svg',
    icon: <IconGrcPanel className="w-5 h-5" />,
    desc: "Custom GRC (Glass Reinforced Concrete) panel fabrication and installation for decorative facades, columns, cornices and screens. Lightweight, durable and weatherproof for Dubai's climate.",
    features: [
      'Custom mold-cast decorative GRC panels',
      'Facade cladding, columns and cornice work',
      'Perforated GRC screens for shading and privacy',
      'UV and weather-resistant factory finish',
    ],
    highlights: ['Custom Molded', 'Weatherproof', 'Lightweight Strength'],
  },
  {
    id: '19',
    slug: 'window-carton-work',
    category: 'windows',
    badge: 'Careful Handling',
    tagline: 'Window Frame Fitting, Packing & Protection',
    title: 'Window Carton Work',
    timeline: '1–2 Days Turnaround',
    image: '/Services/Window Carton Work.svg',
    icon: <IconCarton className="w-5 h-5" />,
    desc: 'Careful fitting, cartoning and edge protection of window frames and glass panels during installation, ensuring scratch-free, secure delivery and fixing on site.',
    features: [
      'Protective carton packing for frames and glass',
      'Safe transport and on-site handling',
      'Precise frame alignment and fixing',
      'Sealant and trim finishing after installation',
    ],
    highlights: ['Scratch Free', 'Secure Fixing', 'Neat Trim Finish'],
  },
  {
    id: '20',
    slug: 'glass-work',
    category: 'windows',
    badge: 'Clear & Custom Cut',
    tagline: 'Glass Partitions, Mirrors & Glazing',
    title: 'Glass Work',
    timeline: '2–4 Days Turnaround',
    image: '/Services/Glass Work.svg',
    icon: <IconGlass className="w-5 h-5" />,
    desc: 'Custom glass cutting and installation for shower enclosures, partitions, mirrors, tabletops and balustrades. Tempered and laminated glass options for safety and style.',
    features: [
      'Tempered glass shower enclosures and partitions',
      'Custom-cut mirrors and tabletop glass',
      'Frameless glass balustrades and railings',
      'Safety film and laminated glass options',
    ],
    highlights: ['Tempered Glass', 'Custom Cut', 'Frameless Finish'],
  },
  {
    id: '21',
    slug: 'flat-decor',
    category: 'interior',
    badge: 'Styled & Ready',
    tagline: 'Apartment Styling & Decor Setup',
    title: 'Flat Decor',
    timeline: '2–5 Days Turnaround',
    image: '/Services/Flat Decor.svg',
    icon: <IconDecor className="w-5 h-5" />,
    desc: 'Styling and decor setup for apartments, from curtains and wall art to furniture arrangement and accent lighting, so your flat feels complete and move-in ready.',
    features: [
      'Curtain, blind and soft furnishing setup',
      'Wall art, mirrors and decor placement',
      'Furniture arrangement and accent lighting',
      'Move-in ready styling for rentals and sales',
    ],
    highlights: ['Move-In Ready', 'Styled Layout', 'Accent Lighting'],
  },
  {
    id: '22',
    slug: 'floor-polish',
    category: 'maintenance',
    badge: 'Mirror Finish',
    tagline: 'Marble, Granite & Tile Floor Polishing',
    title: 'Floor Polish',
    timeline: '1–2 Days Turnaround',
    image: '/Services/Floor Polish.svg',
    icon: <IconFloorPolish className="w-5 h-5" />,
    desc: 'Diamond grinding and polishing for marble, granite and terrazzo floors that brings back a mirror-like shine and removes scratches, stains and dullness.',
    features: [
      'Diamond grinding for scratch and stain removal',
      'Marble, granite and terrazzo polishing',
      'Crystallization for long-lasting shine',
      'Anti-slip coating option for safety',
    ],
    highlights: ['Mirror Shine', 'Scratch Removal', 'Anti-Slip Option'],
  },
  {
    id: '23',
    slug: 'cleaning-work',
    category: 'maintenance',
    badge: 'Move-In Ready',
    tagline: 'Post-Renovation & Deep Cleaning',
    title: 'Cleaning Work',
    timeline: 'Same-Day Service',
    image: '/Services/Cleaning Work.svg',
    icon: <IconCleaning className="w-5 h-5" />,
    desc: 'Deep cleaning and post-renovation cleanup that clears dust, paint residue and construction debris, leaving your home spotless and ready to move into.',
    features: [
      'Post-renovation dust and debris removal',
      'Deep kitchen and bathroom sanitization',
      'Window, glass and fixture cleaning',
      'Move-in and move-out cleaning packages',
    ],
    highlights: ['Same-Day Service', 'Deep Sanitized', 'Move-In Ready'],
  },
  {
    id: '24',
    slug: 'custom-projects',
    category: 'renovation',
    badge: 'Bespoke Requests',
    tagline: 'Custom Projects, Handyman & Special Works',
    title: 'And Much More',
    timeline: 'Tailored Solutions',
    image: '/Services/And Much More.png',
    icon: <IconClock className="w-5 h-5" />,
    desc: 'We handle custom requests and specialized projects. Whether you have an architect drawing or a unique home improvement idea, we bring it to life.',
    features: [
      'Custom architectural and interior modifications',
      'Specialized handyman and property touch-ups',
      'Terrace, garden, and exterior enhancements',
      'Dedicated project consultation and turnkey delivery',
    ],
    highlights: ['Tailored Scope', 'Free Site Survey', '1-Yr Warranty'],
  },
];
