import React from 'react';
import {
  IconDrop,
  IconBolt,
  IconTools,
  IconHome,
  IconBuilding,
  IconGear,
  IconCctv,
  IconClock,
} from './Icons';

export const servicesList = [
  {
    id: '01',
    slug: 'full-home-renovation',
    category: 'renovation',
    badge: 'Turnkey Makeover',
    tagline: 'Complete Villa & Flat Renovation',
    title: 'Full Home Renovation',
    timeline: '2–4 Weeks Turnaround',
    image: '/Services/Home Renovation.png',
    icon: <IconHome className="w-5 h-5" />,
    desc: 'Complete home upgrades managed end-to-end. We take care of demolition, porcelain tiling, false ceilings, lighting, and custom joinery with zero headache.',
    features: [
      'Complete apartment and villa makeovers',
      'Open-concept kitchen and living layouts',
      'Italian & Spanish porcelain floor tiling',
      'Gypsum false ceilings with indirect warm LED lights',
    ],
    highlights: ['Turnkey Scope', 'Free 3D Layout', '1-Yr Warranty'],
  },
  {
    id: '02',
    slug: 'plumbing-bathroom-remodel',
    category: 'mep',
    badge: 'Fast 5–7 Days',
    tagline: 'Modern Bathrooms & Pipe Repairs',
    title: 'Plumbing & Bathroom Remodel',
    timeline: 'Prompt Same-Day Response',
    image: '/Services/Plumbing.png',
    icon: <IconDrop className="w-5 h-5" />,
    desc: 'From fixing stubborn concealed leaks to building modern walk-in rain showers. Our licensed plumbers install fixtures that look stunning and never leak.',
    features: [
      'Concealed pipe leak detection and re-piping',
      'Walk-in glass shower enclosures and rain showers',
      'Modern floating vanity units and toilets',
      'Central water heater replacement and booster pumps',
    ],
    highlights: ['Leak Free Guarantee', 'Grohe / Kohler', 'Clean Finish'],
  },
  {
    id: '03',
    slug: 'electrical-lighting',
    category: 'mep',
    badge: 'Certified Safe',
    tagline: 'Rewiring, DB Boxes & Chandeliers',
    title: 'Electrical & Modern Lighting',
    timeline: 'Safe & Certified Work',
    image: '/Services/Electrical.png',
    icon: <IconBolt className="w-5 h-5" />,
    desc: 'Keep your property safe with clean electrical work. We handle distribution board (DB) upgrades, complete rewiring, architectural LED strips, and chandeliers.',
    features: [
      'Distribution board (DB) circuit breaker upgrades',
      'Safe whole-home rewiring and extra wall sockets',
      'Heavy chandelier installation and magnetic track lights',
      'Smart switches, dimmers, and ambient mood lighting',
    ],
    highlights: ['Certified Electricians', 'Fire Safe Cable', 'Load Tested'],
  },
  {
    id: '04',
    slug: 'custom-carpentry-joinery',
    category: 'woodwork',
    badge: 'In-House Workshop',
    tagline: 'Made-To-Measure Cabinets & Wardrobes',
    title: 'Custom Carpentry & Joinery',
    timeline: 'Factory Direct Quality',
    image: '/Services/Carpenter.png',
    icon: <IconTools className="w-5 h-5" />,
    desc: 'Custom furniture manufactured in our local workshop to fit your exact room measurements. Soft-close hinges, premium veneers, and durable moisture-resistant wood.',
    features: [
      'Modular kitchen cabinets with quartz countertops',
      'Floor-to-ceiling built-in wardrobes and walk-ins',
      'Solid wood interior doors with magnetic latches',
      'Fluted acoustic wood paneling and media feature walls',
    ],
    highlights: ['German Soft-Close', 'Custom Sizing', 'Durable Wood'],
  },
  {
    id: '05',
    slug: 'civil-construction-works',
    category: 'civil',
    badge: 'Solid Structural Quality',
    tagline: 'Acoustic Walls, Extensions & Screeding',
    title: 'Civil & Construction Works',
    timeline: 'Precise Clean Work',
    image: '/Services/Construction.png',
    icon: <IconBuilding className="w-5 h-5" />,
    desc: 'Need an extra bedroom, home office, or room extension? We build sound-insulated gypsum partitions, blockwork walls, floor screeding, and outdoor tiling.',
    features: [
      'Soundproof gypsum wall partitions with glass wool',
      'Room extensions and internal wall removals',
      'Precision laser floor screeding and leveling',
      'Balcony expansion, waterproofing, and patio tiling',
    ],
    highlights: ['Acoustic Rated', 'Smooth Finish', 'Structural Care'],
  },
  {
    id: '06',
    slug: 'metal-fabrication-gates',
    category: 'civil',
    badge: 'Custom Fabricated',
    tagline: 'Villa Driveway Gates, Railings & Stairs',
    title: 'Metal Fabrication & Gates',
    timeline: 'Rust-Proof Powder Coating',
    image: '/Services/Fabrication.png',
    icon: <IconGear className="w-5 h-5" />,
    desc: 'Strong, stylish metalwork custom-welded to your specifications. Automatic motorized driveway gates, stainless steel stair railings, and modern pergolas.',
    features: [
      'Custom motorized sliding & swinging villa driveway gates',
      'Stainless steel 316 and tempered glass balcony railings',
      'Custom metal staircases and outdoor patio pergolas',
      'Window security grills and aluminum shade structures',
    ],
    highlights: ['Rust Protected', 'Italian Motors', 'Heavy Duty Steel'],
  },
  {
    id: '07',
    slug: 'cctv-camera-installation',
    category: 'mep',
    badge: 'Live Mobile Access',
    tagline: 'HD Cameras, Video Doorbells & Access',
    title: 'CCTV & Camera Installation',
    timeline: 'Clean Concealed Wiring',
    image: '/Services/Camera Installation.png',
    icon: <IconCctv className="w-5 h-5" />,
    desc: 'Monitor your villa or apartment 24/7 from your smartphone. We install high-resolution 4K night-vision cameras, smart video doorbells, and digital biometric locks.',
    features: [
      '4K ultra HD cameras with color night vision',
      'Instant mobile phone alerts on iOS & Android',
      'Smart video doorbells and biometric fingerprint locks',
      'Villa perimeter coverage with hidden cabling',
    ],
    highlights: ['Hikvision / Dahua', 'Mobile App Setup', 'Concealed Cables'],
  },
  {
    id: '08',
    slug: 'custom-projects',
    category: 'renovation',
    badge: 'Bespoke Requests',
    tagline: 'Custom Projects, Handyman & Special Works',
    title: 'And Much More',
    timeline: 'Tailored Solutions',
    image: '/Services/And Much More.png',
    icon: <IconClock className="w-5 h-5" />,
    desc: 'We handle custom requests and specialized projects. Whether you have an architect drawing or a unique home improvement idea, we bring it to life.',
    features: [
      'Custom architectural and interior modifications',
      'Specialized handyman and property touch-ups',
      'Terrace, garden, and exterior enhancements',
      'Dedicated project consultation and turnkey delivery',
    ],
    highlights: ['Tailored Scope', 'Free Site Survey', '1-Yr Warranty'],
  },
];
